#version: '3'
#services:
#  app:
#    build: .
#    volumes:
#      - .:/app
#    command: npm start
#    ports:
#      - 3000:3000
#  nginx:
#    image: nginx:latest
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#    ports:
#      - 80:80
#    depends_on:
#      - app

version: '3'
services:
  nginx:
    image: 'nginx:stable-alpine'
    container_name: 'nginx_fe_aman'
    ports:
      - '80:80'
    volumes:
      - './dist:/var/www/html'
      - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
  npm:
    image: 'node:20'
    container_name: 'npm-fe-aman'
    volumes:
      - './src:/var/www/html'
    working_dir: /var/www/html
    entrypoint:
      - npm

